name = "ocdATTracker"
author = "Chiviguagua"
version = "1.0"
category = "Trackmania"
script = "Main.as"
description = "Track Author Time progress for the OCD campaign in Trackmania."
game_version = "*"
